CREATE TABLE IF NOT EXISTS test_messages (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(250) NOT NULL,
  text TEXT NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  is_approved BOOLEAN DEFAULT FALSE,
  is_edited BOOLEAN DEFAULT FALSE
);